# Generated by Django 5.1.4 on 2026-09-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='批次票号')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('submitted_rows', models.PositiveIntegerField(verbose_name='提交行数')),
                ('failed_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='问题行号')),
                ('fail_reason', models.CharField(blank=True, max_length=200, verbose_name='失败原因')),
                ('row_keys', models.TextField(blank=True, verbose_name='本批新行主键串')),
                ('created_by', models.CharField(max_length=64, verbose_name='提交人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspection.batchattempt', verbose_name='所属批次')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
